import { CaretDown, ChatCircleDots, Check, ListBullets, MagicWand, Pause, Play, Sparkle, Stop, TextAa, Timer } from "@phosphor-icons/react";
import { useEffect, useRef, useState } from "react";
import { ChatPanel } from "./ChatPanel";
import { ComfortableEditor } from "./ComfortableEditor";
import { InsightContent } from "./InsightContent";
import { RelationshipGraph } from "./RelationshipGraph";
import { ToolButton } from "./ToolButton";
import type { ActiveWritingSession, EditorPreferences, LibraryItem, ModelConfig, NovelProject, SavedChapter, StoryAnalysis, WritingSession, WritingSkill } from "../types/story";

const fontLabels: Record<EditorPreferences["fontFamily"], string> = { songti: "宋体", heiti: "黑体", kaiti: "楷体", system: "系统字体" };
const paragraphLabels: Record<EditorPreferences["paragraphStyle"], string> = { compact: "紧凑", body: "正文", relaxed: "舒展" };
const fontOptions: Array<{ value: EditorPreferences["fontFamily"]; label: string }> = [{ value: "songti", label: "宋体" }, { value: "heiti", label: "黑体" }, { value: "kaiti", label: "楷体" }, { value: "system", label: "系统字体" }];
const sizeOptions: EditorPreferences["fontSize"][] = [15, 16, 17, 18, 19, 20];

function formatDuration(seconds: number) {
  const minutes = Math.floor(seconds / 60);
  return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
}

export function WritingView({ activeChapter, chapterTitle, draft, setDraft, wordCount, aiBusy, generateContinuation, setChatOpen, chatOpen, rightPanel, setRightPanel, storyAnalysis, agentBusy, onRunAgent, modelConfig, savedChapters, project, library, skills, editorPreferences, onEditorPreferencesChange, writingSession, writingSessionSeconds, lastWritingSession, onToggleWritingSession, onEndWritingSession, onOpenWritingHistory }: { activeChapter: number; chapterTitle: string; draft: string; setDraft: (value: string) => void; wordCount: number; aiBusy: boolean; generateContinuation: () => void; setChatOpen: (value: boolean) => void; chatOpen: boolean; rightPanel: "insight" | "graph"; setRightPanel: (value: "insight" | "graph") => void; storyAnalysis: StoryAnalysis | null; agentBusy: boolean; onRunAgent: () => void; modelConfig: ModelConfig; savedChapters: SavedChapter[]; project?: NovelProject; library: LibraryItem[]; skills: WritingSkill[]; editorPreferences: EditorPreferences; onEditorPreferencesChange: (next: EditorPreferences) => void; writingSession: ActiveWritingSession | null; writingSessionSeconds: number; lastWritingSession?: WritingSession; onToggleWritingSession: () => void; onEndWritingSession: () => void; onOpenWritingHistory: () => void }) {
  const [openMenu, setOpenMenu] = useState<"style" | "font" | "size" | null>(null);
  const toolbarRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const close = (event: MouseEvent) => { if (!toolbarRef.current?.contains(event.target as Node)) setOpenMenu(null); };
    window.addEventListener("mousedown", close); return () => window.removeEventListener("mousedown", close);
  }, []);
  const updatePreference = <K extends keyof EditorPreferences>(key: K, value: EditorPreferences[K]) => { onEditorPreferencesChange({ ...editorPreferences, [key]: value }); setOpenMenu(null); };
  const netWords = writingSession ? wordCount - writingSession.startWordCount : 0;
  const speed = writingSessionSeconds > 0 ? Math.max(0, Math.round(netWords / (writingSessionSeconds / 60))) : 0;
  const lastNetWords = lastWritingSession ? lastWritingSession.endWordCount - lastWritingSession.startWordCount : null;
  const lastSpeed = lastWritingSession && lastWritingSession.activeSeconds > 0 ? Math.max(0, Math.round(lastNetWords! / (lastWritingSession.activeSeconds / 60))) : null;
  return <div className="writing-layout">
    <section className="editor-zone">
      <div className="editor-breadcrumb"><span>第一卷 · 回城</span><span>/</span><strong>第{activeChapter || "—"}章 {chapterTitle}</strong><span className="saved-indicator"><Check size={13} />已保存</span></div>
      <div className="editor-toolbar"><div className="editor-tools" ref={toolbarRef}><div className="toolbar-menu"><ToolButton icon={TextAa} label="文字样式" active={openMenu === "style"} onClick={() => setOpenMenu(openMenu === "style" ? null : "style")} />{openMenu === "style" && <div className="format-menu style-menu" role="menu"><p>段落间距</p>{(["compact", "body", "relaxed"] as const).map((style) => <button key={style} className={editorPreferences.paragraphStyle === style ? "selected" : ""} onClick={() => updatePreference("paragraphStyle", style)}>{paragraphLabels[style]}<small>{style === "compact" ? "1.75 倍行距" : style === "body" ? "2.05 倍行距" : "2.35 倍行距"}</small></button>)}</div>}</div><span className="tool-divider" /><div className="toolbar-menu"><button className={`font-control ${openMenu === "font" ? "active" : ""}`} onClick={() => setOpenMenu(openMenu === "font" ? null : "font")}>{fontLabels[editorPreferences.fontFamily]} <CaretDown size={13} /></button>{openMenu === "font" && <div className="format-menu" role="menu"><p>正文字体</p>{fontOptions.map((option) => <button key={option.value} className={editorPreferences.fontFamily === option.value ? "selected" : ""} onClick={() => updatePreference("fontFamily", option.value)}>{option.label}</button>)}</div>}</div><div className="toolbar-menu"><button className={`font-control ${openMenu === "size" ? "active" : ""}`} onClick={() => setOpenMenu(openMenu === "size" ? null : "size")}>{editorPreferences.fontSize} <CaretDown size={13} /></button>{openMenu === "size" && <div className="format-menu size-menu" role="menu"><p>字号</p>{sizeOptions.map((size) => <button key={size} className={editorPreferences.fontSize === size ? "selected" : ""} onClick={() => updatePreference("fontSize", size)}>{size} px</button>)}</div>}</div><ToolButton icon={ListBullets} label="段落间距" active={openMenu === "style"} onClick={() => setOpenMenu(openMenu === "style" ? null : "style")} /></div><div className="editor-meta">{wordCount.toLocaleString()} 字 <span>·</span> {paragraphLabels[editorPreferences.paragraphStyle]}排版</div></div>
      <ComfortableEditor activeChapter={activeChapter} chapterTitle={chapterTitle} draft={draft} setDraft={setDraft} preferences={editorPreferences} />
      <div className="writing-session" aria-live="polite"><div className="session-stat"><span>本次码字</span><strong>{writingSession ? `${netWords >= 0 ? "+" : ""}${netWords.toLocaleString()} 字` : "尚未开始"}</strong></div><div className="session-stat"><span>码字速度</span><strong>{writingSession ? `${speed.toLocaleString()} 字/分` : "—"}</strong></div><div className="session-stat"><span>有效时长</span><strong>{writingSession ? formatDuration(writingSessionSeconds) : "00:00:00"}</strong></div><div className="session-actions"><button className={`session-toggle ${writingSession?.status === "running" ? "running" : ""}`} onClick={onToggleWritingSession}>{writingSession?.status === "running" ? <Pause size={15} weight="fill" /> : <Play size={15} weight="fill" />}{writingSession?.status === "running" ? "暂停" : writingSession ? "继续" : "开始码字"}</button>{writingSession && <button className="session-stop" onClick={onEndWritingSession} aria-label="结束并记录本次码字"><Stop size={15} weight="fill" />结束</button>}</div>{!writingSession && lastWritingSession && <p className="last-session"><Timer size={13} />最近一次：{lastNetWords! >= 0 ? "+" : ""}{lastNetWords!.toLocaleString()} 字 · {formatDuration(lastWritingSession.activeSeconds)} · {lastSpeed?.toLocaleString() || "0"} 字/分 <button onClick={onOpenWritingHistory}>查看记录</button></p>}</div>
      <div className="editor-footer"><span><Sparkle size={15} weight="fill" />AI 会参考本章设定、前情和人物状态</span><button className="generate-button" onClick={generateContinuation} disabled={aiBusy}>{aiBusy ? <span className="loading-mark" /> : <MagicWand size={17} weight="fill" />}{aiBusy ? "正在续写" : "续写 800 字"}</button></div>
    </section>
    <aside className="insight-panel"><div className="panel-tabs"><button className={rightPanel === "insight" ? "selected" : ""} onClick={() => setRightPanel("insight")}>本章洞察</button><button className={rightPanel === "graph" ? "selected" : ""} onClick={() => setRightPanel("graph")}>关系图</button><ToolButton icon={ChatCircleDots} label="打开 AI 对话" active={chatOpen} onClick={() => setChatOpen(!chatOpen)} /></div>{rightPanel === "insight" ? <InsightContent analysis={storyAnalysis} agentBusy={agentBusy} onRunAgent={onRunAgent} /> : <RelationshipGraph analysis={storyAnalysis} />}{chatOpen && <ChatPanel onClose={() => setChatOpen(false)} config={modelConfig} project={project} chapters={savedChapters} analysis={storyAnalysis} library={library} skills={skills} />}</aside>
  </div>;
}
